### ISSUE TITLE
Nite2 no devices found on Ubuntu 16.04

### ISSUE THREAD

**Issue by paul-mesnilgrente** [occipital/OpenNI2#112]
Hello everyone!

I have installed libfreenect2 using the README.md on github and it works fine. So I have installed OpenNI2 with the package manager of Ubuntu too.

But I am having trouble with Nite2. I have runned `./install.sh` without problems. But when I run the sample `./UserViewer`, the device is not recognized :

```text
Failed to open device
    DeviceOpen using default: no devices found
```

So I have followed [this](http://stackoverflow.com/questions/39133646/how-to-setup-openni2-and-nite-with-libfreenect2-for-skeleton-tracking-on-osx) but the result is the same.

Any idea ? I am on this since 3 days and I am desperate.

Thank you very much.

**Comment by Sawsie** [comment]
Hi, 
I have the same problem on Ubuntu 14.04! 
Have you found a solution?

**Comment by paul-mesnilgrente** [comment]
Yes, I have removed every manual install of OpenNI2 and libfreenect2 (look into `/usr/local/lib` and `/usr/local/include`). Then I have executed this:

```bash
# Install OpenNI2
sudo apt-get install -y libopenni2-dev openni2-utils

# Install libfreenect2
sudo apt-get install -y build-essential cmake pkg-config libusb-1.0-0-dev libturbojpeg
git clone https://github.com/OpenKinect/libfreenect2.git
mkdir libfreenect2/build && cd libfreenect2/build
cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR/freenect2 -DENABLE_VAAPI=OFF ..
make
sudo make install
# Set up udev rules for device access
sudo cp ../platform/linux/udev/90-kinect2.rules /etc/udev/rules.d/
sudo make install-openni2

# Install NiTE2
# becarefull with this URL, you must have a 64 bit OS
wget 'http://download.dahoo.fr/Ressources/openNi/last%20version%20Nite/NiTE-Linux-x64-2.2.tar1.zip'
unzip NiTE-Linux-x64-2.2.tar1.zip
tar xjf NiTE-Linux-x64-2.2.tar.bz2
rm NiTE-Linux-x64-2.2.tar1.zip NiTE-Linux-x64-2.2.tar.bz2

cd NiTE-Linux-x64-2.2
sudo ./install.sh

# patch: http://stackoverflow.com/questions/39133646/how-to-setup-openni2-and-nite-with-libfreenect2-for-skeleton-tracking-on-osx
sudo ln -s $INSTALL_DIR/freenect2/lib/OpenNI2/Drivers/libfreenect2-openni2.so $INSTALL_DIR/NiTE-Linux-x64-2.2/Samples/Bin/OpenNI2/Drivers/
```

Tell me if this worked for you :)

**Comment by Sawsie** [comment]
Many Thanks! It works! :+1:
