### ISSUE TITLE
Cannot read .oni file as filename

### ISSUE THREAD

**Issue by vinayramb** [occipital/OpenNI2#118]
The OpenNi.h header file recommends the following in order to read a recording saved as a .oni file,
"**Opening a file device is done by passing its path as the uri to the @ref Device::open() method."**

However, when I try the above, the following error shows up,
"**DeviceOpen: Couldn't open device**". 

Is there a fix around this? How does one read a recorded .oni file?

Thank you!

**Comment by ty-dev** [comment]
@jselikof is this something you have any work around for?
