### ISSUE TITLE
No devices found when using Python

### ISSUE THREAD

**Issue by kityan147** [occipital/OpenNI2#131]
I am using the kinect v1 and raspberry pi 3 for this.

I successfully installed the OpenNI2 and used the primesense python binding. I successfully run the demo like freenect-camtest, freenect-glview without any problem. However, when I use the python
`from primesense import openni2

openni2.initialize()
dev = openni2.Device.open_any()`

It returns that there is no devices found. It is so weird.

Thank you for the help and sorry for my bad english.

**Comment by Looki2000** [comment]
Have you managed to fix that? I'm currently facing exactly the same issue.
