### ISSUE TITLE
Support for WIndows Store Apps

### ISSUE THREAD

**Issue by rickyaires** [occipital/OpenNI2#14]
At a first glance trying to use PrimeSense Carmine 1.09 is not possible within a Windows Store App. Is there a limitation in terms of driver support. The device is simply not recognized inside the application. Would it be possible to access the scanner inside a Store app.

Thanks

**Comment by ntisserand** [comment]
Hello @rickyaires, and apologies for the late answer.

We have no specific plans on making OpenNI suitable for Windows Store Apps development, but are open to contributions.

This might not be an easy one to tackle, though. I might be mistaken, but last time I checked, communicating with a custom USB device from a Windows Store Apps didn't look exactly straightforward.

Thanks for letting us know.
