### ISSUE TITLE
"Can't Determine Host Platform." When running MAKE

### ISSUE THREAD

**Issue by xoxota99** [occipital/OpenNI2#145]
Trying to build this on NVidia Jetson TX2 (aarch64). Following the instructions in README.MD, as soon as I run make, I get this error: "ThirdParty/PSCommon/BuildSystem/CommonDefs.mak:22: *** Can't determine host platform.  Stop."

make gives no other output, other than this error. What am I doing wrong? I can edit the CommonDefs.mak file, but I don't actually know if the aarch64 platform is "close enough" to the arm platform for build purposes.

**Comment by xoxota99** [comment]
I Tried just running apt install openni2-utils libopenni2-dev , and that seems to have worked. No idea what version that package is, how it relates to this repo, or anything.

**Comment by xoxota99** [comment]
Nevermind, I just used the repo at https://github.com/mikeh9/OpenNI2-TX1 . Works on TX2 as well.

**Comment by wangxuanzhao** [comment]
@xoxota99 what's your device? xtion or kinect?

**Comment by xoxota99** [comment]
I'm using the structure.io ZED camera. (https://structure.io/ )
