### ISSUE TITLE
manually read streams in oni recording

### ISSUE THREAD

**Issue by roccopietrini** [occipital/OpenNI2#146]
Hi,
I was writing an application to extract all the frame contained in a .oni recording. I set playback speed to -1 (manual), create and start two streams (depth and color) and read them manually using readframe in a loop. However seems that manual mode is not respected as if simply read frames for one of the streams seek  forward also the other one (some frames are skipped). 
Working solution is to read one stream after the other, reinitializing OpenNI2 in between or to use seek function before each readframe. As anyone experienced this? Is this a known bug?
Second question, does anyone know if the frameindex is guaranteed to be sequential in a stream and continuous? (without skipping any number between 1 and N)

**Comment by mvm9289** [comment]
That's exactly how seek() is supposed to work: https://github.com/occipital/OpenNI2/blob/master/Include/OpenNI.h#L1766

**Comment by roccopietrini** [comment]
Thank you for the quick response, however there is something not clear to me. I know about the seek function and how it works, but my question is.. why is necessary in manual mode? Suppose the following code where I first read all the depth frames and then the color frames manually:

depthStream.create(device, openni::SensorType::SENSOR_DEPTH);
depthStream.start();
for(unsigned int i=1; i<playbackControl->getNumberOfFrames(depthStream); i++)
    depthStream.readFrame(&depthFrame);
    ....

colorstream.create(device, openni::SensorType::SENSOR_COLOR);
colorstream.start();

At this point the colorstream I'd expect to be at frameindex = 1 since I didn't read any frame in it.. but it's actually at a frameindex more or less equal to the last one of the depth stream, as if readstream use seek internally and hence advance both streams (even if I din't even create the color one! )
Is this correct?
Thank you for your time!

Second question about the frameindex.. frameindex of the last frame, is guaranteed to be equal to what is returned by function playbackControl->getNumberOfFrames(depthStream) ? In other words can I have missing frameindex in the stream?

**Comment by mvm9289** [comment]
It's been a long time since I've dealt with these mechanisms, but I think that is indeed the expected behavior. All streams share a common timeline of some sort.

> Second question about the frameindex.. frameindex of the last frame, is guaranteed to be equal to what is returned by function playbackControl->getNumberOfFrames(depthStream) ? In other words can I have missing frameindex in the stream?

It is guaranteed for a specific stream. However, as far as I'm aware, it isn't guaranteed that getNumberOfFrames(depthStream) == getNumberOfFrames(colorStream).

What I usually did when I was working with OpenNI was to have a "stream of interest" (the most important one for your application needs, in my case depth) which I would process all frames from, and then get the associated frames from all other streams.

I hope I made myself clear enough.

**Comment by roccopietrini** [comment]
Exactly confirming what I was thinking about. Thank you very much for your time!
