### ISSUE TITLE
Issue with Occipital: structure sensor

### ISSUE THREAD

**Issue by funfrancis** [occipital/OpenNI2#16]
Hi

I get the following error message when I open NiViewer in Linux x64
kindly help me to resolve my issue..

I have attached a screen-shot of the error that I received
![screenshot from 2014-07-04 10_36_33](https://cloud.githubusercontent.com/assets/8066513/3479935/c94fcc00-0359-11e4-9e0c-4aed19829955.png)
 of the error

**Comment by ntisserand** [comment]
Hi @funfrancis,

This is a rather old issue, with unknown status, so I'm closing it for now. Please reopen if still in trouble.

Thanks!
