### ISSUE TITLE
Where is the file Kinect.h?

### ISSUE THREAD

**Issue by jiapei100** [occipital/OpenNI2#169]
Hi, ALL:

- Where is `#include <Kinect.h>` in file [Kinect2Device.cpp](https://github.com/structureio/OpenNI2/blob/kinect2/Source/Drivers/Kinect2/Kinect2Device.cpp), [Kinect2Driver.cpp](https://github.com/structureio/OpenNI2/blob/kinect2/Source/Drivers/Kinect2/Kinect2Driver.cpp), and [DepthKinect2Stream.h](https://github.com/structureio/OpenNI2/blob/kinect2/Source/Drivers/Kinect2/DepthKinect2Stream.h) ???
- And where are the implementation of those forward declarations in file [Kinect2StreamImpl.h](https://github.com/structureio/OpenNI2/blob/kinect2/Source/Drivers/Kinect2/Kinect2StreamImpl.h) ???
```C++
struct IKinectSensor;
struct ICoordinateMapper;
struct IFrameDescription;
struct IColorFrameReader;
struct IDepthFrameReader;
struct IInfraredFrameReader;
```

**Comment by dromer** [comment]
This comes from the Kinect SDK

**Comment by jiapei100** [comment]
@dromer 
Thank you for your prompt reply. But, is it ONLY for Windows? Isn't there at least a library for Linux?

**Comment by dromer** [comment]
There is libfreenect, but this is unrelated to the Kinect SDK.

**Comment by jiapei100** [comment]
@dromer 

I tried **libfreenect2** already... it seems my **Kinect v2** is NOT working properly. I think **libfreenect** ONLY works for **Kinect v1**, right?

**Comment by jiapei100** [comment]
@dromer 

Working now [https://longervision.github.io/2024/07/08/MachineVision/RGBD/Kinect-2/](https://longervision.github.io/2024/07/08/MachineVision/RGBD/Kinect-2/).

Have to rebuild **OpenNI2** on **Ubuntu 24.04**.

Thank you ...

**Comment by dromer** [comment]
@jiapei100 nice, you're able to build against libfreenect on Linux!

I don't have a Kinect2 and haven't used OpenNI in ages. Glad you got something working!
