### ISSUE TITLE
device not identified

### ISSUE THREAD

**Issue by funfrancis** [occipital/OpenNI2#20]
When I type $lsusb..i get
Bus 001 Device 012: ID 277a:0001  
Bus 003 Device 002: ID 0603:00f2 Novatek Microelectronics Corp. 
Bus 004 Device 003: ID 046d:c018 Logitech, Inc. Optical Wheel Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

kindly help me resolve the error

**Comment by ntisserand** [comment]
@funfrancis @forrest-occipital  Closing this old issue, solved elsewhere. Please reopen if in trouble again.
