### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by Waffle555** [occipital/OpenNI2#23]
I cloned it and downloaded all the required packages. when I try to run make, it give me this error. I looked at some solutions online, they seem to be related to "link". I'm new to this and have no idea what to do with this error. Can I get some help please? thanks a lot!

    g++ -o ../../../Bin/x86-Release/libOpenNI2.jni.so ./../../../Bin/Intermediate/x86-Release/libOpenNI2.jni.so/OpenNI.jni.o ./../../../Bin/Intermediate/x86-Release/libOpenNI2.jni.so/org_openni_NativeMethods.o  -L../../../Bin/x86-Release -lOpenNI2 -Wl,--no-undefined -shared
    /usr/lib/i386-linux-gnu/libc_nonshared.a(stack_chk_fail_local.oS): In function `__stack_chk_fail_local':
    (.text+0x10): undefined reference to `__stack_chk_fail'
    collect2: error: ld returned 1 exit status
    make[1]: *** [../../../Bin/x86-Release/libOpenNI2.jni.so] Error 1
    make[1]: Leaving directory `/home/Waffle555/OpenNI2/Wrappers/java/OpenNI.jni'
    make: *** [Wrappers/java/OpenNI.jni] Error 2

**Comment by ntisserand** [comment]
Hi, and apologies for the late answer.

Your problem is related to Java bindings not building, 

Are you still getting this with the latest `unstable` branch, where they are disabled by default?

**Comment by jselikof** [comment]
Please use the develop branch, and follow the README, for your development efforts.
