### ISSUE TITLE
Color Image Issue SimpleViewer

### ISSUE THREAD

**Issue by PerloDaniele** [occipital/OpenNI2#28]
Hi all,
i try to use OpenNI2 with an old XtionPro 

i can obtain the gray-scale image with NiViewer Tool but SimpleViewer crash with error "unable to find color stream" (it hasn't RGB camera)

now the noobie question:
my final goal is try to use multiple sensors, so i need to continue sperimenting on OpenNi 1.5 or OpenNi 2 (if there are no other issues without rgb camera)?

**Comment by ntisserand** [comment]
Hello @PerloDaniele, and sorry for the late answer.

OpenNI can do depth-only streaming, but SimpleViewer needs to be modified a bit, for it not to request the color stream. It's not hard to do, I can show you how if you didn't figure it out already.

Multi-sensor setups should also work. Take a look at the `MultiDepthViewer` sample. A kind user also recently shared some multi-kinect setup code here, that you may find useful: https://github.com/occipital/OpenNI2/issues/37.

Closing the issue for now. Please reopen it if you're still stuck.

Thanks!
