### ISSUE TITLE
DeviceOpen using default: no devices found

### ISSUE THREAD

**Issue by denistribouillois** [occipital/OpenNI2#31]
Hello, I'm trying to use OpenNI with a Kinect, but after extracting the tarball and running the ./install.sh I try to launch Sample (like SimpleViewer) but I got the error : 
"After initialization:

SimpleViewer: Device open failed:
	DeviceOpen using default: no devices found"

I think it's a problem with drivers or usb privileges since I can see the device with "lsusb".
The file "/etc/udev/rules.d/557-primesense-usb.rules" as been created.
I hope you can help me.
Thanks.

**Comment by Queuecumber** [comment]
Looks like the kinect build is dependent on windows and the kinect sdk

**Comment by pierreenel** [comment]
What if I have a Kinect One and I am on Ubuntu, only libfreenect2 will work for the Kinect One no? Does this mean I can't use OpenNI2 with Kinect One on Linux?

**Comment by ataiya** [comment]
I have never tried kinect. It's 30FPS max though, so I doubt it would work as well.

**Comment by MasWag** [comment]
I and hanyazou wrote wrappers. Look at the issue https://github.com/OpenKinect/libfreenect2/issues/243 .

**Comment by andreaskoepf** [comment]
You can check if a file cannot be loaded with ```strace SimpleRead 2>&1 | less``` .

If you are using the pre-built binaries on  Ubuntu 14.04 this problem results from a missing libudev.0.so.

You could either build the OpenNI driver from source or create a symlink for libudev.0.so ... e.g.
```
sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.3.5 /lib/x86_64-linux-gnu/libudev.so.0
```
see the [stackoverflow answers].(http://stackoverflow.com/questions/19938830/openni2-and-asus-xtion-pro-live-device-not-found)

**Comment by jselikof** [comment]
@denistribouillois did you have success with the Kinect after following @andreaskoepf 's note?

**Comment by denistribouillois** [comment]
Hello, we ended up doing our project under windows with the Microsoft SDK. I didn't try andreaskoepf's note since we finished our project last year. Sorry.

**Comment by jselikof** [comment]
Confirmed suggestion to create symlink for libudev.0 given by @andreaskoepf works.

**Comment by krishna433** [comment]
Problem was solved by creating symlink for libusdev.0  as suggested by @andreaskoepf.

Thank you @andreaskoepf
