### ISSUE TITLE
Building OpenNI2 for Android fails on Windows

### ISSUE THREAD

**Issue by Windowsfreak** [occipital/OpenNI2#32]
symlink is an alien concept for windows.
https://github.com/occipital/OpenNI2/blob/master/Packaging/ReleaseVersion.py#L113

    Creating installer for OpenNI 2.2 android
    Traceback (most recent call last):
     File "C:\Software\OpenNI2\Packaging\ReleaseVersion.py", line 113, in <module>
        os.symlink('../../../', buildDir + '/jni/OpenNI2')
    AttributeError: 'module' object has no attribute 'symlink'

**Comment by jselikof** [comment]
Please use the develop branch.
