### ISSUE TITLE
NI viewer shows "Depth stream is off and color stream is off" message on screen.

### ISSUE THREAD

**Issue by senthilkumaranms** [occipital/OpenNI2#35]
Device detected as Primesense carmine. but NI viewer shows "Depth stream is off and color stream is off" message on screen.

SS connected to Laptop - Windows7.

sensor charging LED is blinking. as if, it is connected to charger. any changes has to be made to make it work?

I tried changing USB ports but no change. images are OFF message showing on screen. 

With the same connection, I opened it in Skanect software. there it working well. only with NIviewer it is not working. what is the reason?

**Comment by ntisserand** [comment]
Hello @senthilkumaranms. "SS" makes me assume you are using the Structure Sensor, since that's the only one on the market that has a rechargeable battery.

I'd like to reproduce your issue, but need to know what version of OpenNI you are trying to use. Can you please give us more information about your setup?

Thanks!

**Comment by senthilkumaranms** [comment]
Yes. I mentioned SS as short form for structure Sensor. 

I have used OpenNI 2.2.0.33 Beta (x86) downloaded from this link http://structure.io/openni.

Setup
--------
- Connected to windows 7 32 bit laptop.

Observations
------------------
- worked in Skanect software. 
- in ni viewer "Depth stream is off and color stream is off" message shown on screen.

**Comment by senthilkumaranms** [comment]
This issue has been resolve SS support team. as given in the open ni2 insruction manual I changed the line of ;USBinterface = 2 to USBinterface = 0. but I did not remove the semicolon preceding the line. I am not aware of this. so I did not get the images. now after receiving support from the SS support team. I fixed it and I am getting the images.

Details of the fix is to remove semicolon

;UsbInterface=0

to

UsbInterface=0

**Comment by shalini-10** [comment]
Hello @Senthilkumaranms,

Can you please tell me how did you make changes in the PS1080.ini ? When I attempted to make changes in the PS1080.ini,  it shows me that PS1080.ini is a read only file and I am not able to make changes.

Can you please help me with this issue?

Thanks,
Addepalli Shalini

**Comment by AlfredoBatz** [comment]
Muchas gracias por decir que era el punto y coma, solo lo borre y me funciono, THANKS
