### ISSUE TITLE
What must be implemented to have a "valid" OpenNI driver

### ISSUE THREAD

**Issue by SethGibson** [occipital/OpenNI2#42]
First off, apologies if this is an inappropriate post for this venue, but I'm not sure where else to ask at this point:

I've written a driver for a soon-to-be released depth sensor and I can run all the samples (SimpleRead, NiViewer, etc), but when I try and run an application that claims to support OpenNI (NiTE, for example), I'm unable to use my driver.  Are there specific resolutions, streams, framerates, properties, etc that MUST be implemented for OpenNI dependent applications to consider a driver as valid?

**Comment by KHeresy** [comment]
As what I know:
The FoV( ONI_STREAM_PROPERTY_VERTICAL_FOV  and  ONI_STREAM_PROPERTY_HORIZONTAL_FOV) are required for coordinate convert (between depth and world).

PrimeSense NiTE requires special resolution (VGA or QVGA), and special properties.
According to the license of NiTE, you can NOT use NiTE with non-PrimeSense products.

https://github.com/VIML/VirtualDeviceForOpenNI2/wiki/About-PrimeSense-NiTE

**Comment by SethGibson** [comment]
Thanks for the info!  I figured it would be as simple as just making sure the depth stream works but I see there's definitely more to it.  Good to know about authorized vs non-authorized hardware as well, I guess NiTE may not be the option I was looking for.  Thanks again!
