### ISSUE TITLE
Sharing device across applications

### ISSUE THREAD

**Issue by smarkan** [occipital/OpenNI2#45]
I am trying to use OpenNI2 with a PrimeSense camera.  I would like to be able to access the same frames from two applications simultaneously.  One of these applications is an existing closed source app, and I am writing the other one.  But I notice when I try running two instances of the SimpleRead demo app, each application only gets half the frames.  Is there a way around this?  Thanks in advance for any help.

**Comment by atuleu** [comment]
I think the easiest is to have one application reading the device, and sending to the other the frame using any IPC mechansim, like memory sharing.

I would say openni should set a lock on the device so two applications could not open it simulatenously.

**Comment by smarkan** [comment]
Thanks for the help.  I agree IPC would be ideal, but since one of the applications is out of my control it sounds like I'm out of luck.
