### ISSUE TITLE
Install OpenNI2 with OpenCV3

### ISSUE THREAD

**Issue by nmante** [occipital/OpenNI2#47]
Any advice on how to install OpenNI2 with OpenCV 3 on Mac OS X Yosemite? I've successfully cloned and installed OpenNI 2 to my computer.  Now using CMAKE to install openCV 3.  For some reason, the CMAKE can't find my libraries even though I'm adding CMAKE variables to the file.

These are the variables the error tells me to use. I'm setting these variables though, and the locations exist.  They contain the .dylib files:

**OPENNI2_LIB_DIR** -> /Users/nmante/Documents/Programming/External_Git_Repos/OpenNI2/Bin/x64-Release/OpenNI2
**OPENNI2_INCLUDE_DIR** -> /Users/nmante/Documents/Programming/External_Git_Repos/OpenNI2/Include

And here is the actual error/warning

**WARNING, OpenNI2 library directory (set by OPENNI2_LIB_DIR variable) is not found or does not have OpenNI2 libraries.**
**WARNING, OpenNI2 include directory (set by OPENNI2_INCLUDE_DIR variable) is not found or does not have OpenNI2 include files.**

**Comment by hcw70** [comment]
If you are using a debian based os, please try https://github.com/hcw70/OpenNI2/wiki or look at https://launchpad.net/~v-launchpad-jochen-sprickerhof-de/+archive/ubuntu/pcl for pre-built ubuntu packages.

CMake then has no problem to find these.

**Comment by jselikof** [comment]
Please check out http://docs.opencv.org/3.0-rc1/d7/df5/tutorial_ug_highgui.html for suggestions on using OpenNI depth sensors with OpenCV.
