### ISSUE TITLE
Structure sensor intrinsics

### ISSUE THREAD

**Issue by bhack** [occipital/OpenNI2#50]
@jrpowers I think you know that @pokeefe shared opencv registration code at https://github.com/Itseez/opencv_contrib/pull/132. 
Can you share structure sensor intrinsics? 
Do you have tried standard opencv stereo calibration pipeline with nexus 9 or other android devices with the registration code?

**Comment by jselikof** [comment]
@bhack please take a look at: http://forums.structure.io/t/intrinsics-for-ios-devices-and-the-structure-sensor-depth-point-cloud-info/4640
