### ISSUE TITLE
Any active community?

### ISSUE THREAD

**Issue by florianletsch** [occipital/OpenNI2#59]
Hey, I am getting started with OpenNI and I'm sure I'll have many questions along the way. Is there any go-to destination for community discussions? I haven't found one so far.

I'd rather prefer that over flooding the Github issues with my naïve questions.

**Comment by blueeaglex** [comment]
Hi florianletsch
I am working on this too.  I am trying to make it work on Android with structure sensor. I got some useful infomation on http://forums.structure.io/t/structure-sensor-on-android/1496.
Now, I have built the JNI warppers to combine it with my app. But I am stuck by "OpenNI.initialize()".  So, would you like to share some progress on your project?

**Comment by florianletsch** [comment]
Kind of. I am using the `primesense` python bindings (which lack any documentation as it seems) and have managed to read and display existing *.oni recordings. For that I am converting the *.oni data to numpy arrays which I am more familiar working with. 

I have no idea if I can the human skeleton model using that approach and am kind of stuck with the prerecorded data for now. Thanks for the link though, I'll browse the structure.io forums I guess.
