### ISSUE TITLE
Kinect not detected when trying with SimpleViewer sample

### ISSUE THREAD

**Issue by florianletsch** [occipital/OpenNI2#62]
Trying to use OpenNI2 for a project, but can't even seem to get past the first obsctaces. I have cloned the `develop` branch and built with `make`. That worked without issues. I am on Mac OS.

Trying to launch the `SimpleViewer` sample.

```sh
git:(develop): /Users/flo/tmp/OpenNI2/Bin/x64-Release/SimpleViewer
dyld: Library not loaded: libOpenNI2.dylib
  Referenced from: /Users/flo/tmp/OpenNI2/Bin/x64-Release/SimpleViewer
  Reason: image not found
[1]    11509 trace trap  /Users/flo/tmp/OpenNI2/Bin/x64-Release/SimpleViewer
```

Apparently I have to link to the compiled library location, I am doing by prepending the library path as follows:

`DYLD_LIBRARY_PATH=/Users/flo/tmp/OpenNI2/Bin/x64-Release/ /Users/flo/tmp/OpenNI2/Bin/x64-Release/SimpleViewer`

This still fails because it doesn't seem to recognize the connected Kinect (v1).

````
After initialization:

SimpleViewer: Device open failed:
	DeviceOpen using default: no devices found
```

The Kinect is connected however. I can confirm this because it is registered as a usb device. Out of `ioreg -p IOUSB` contains:

```
  | | +-o HubDevice@fa130000  <class IOUSBHubDevice, id 0x100003cd2, registered, matched, active, busy 0 (9 ms), retain 15>
  | |   +-o Xbox NUI Motor@fa132000  <class IOUSBDevice, id 0x100003cdc, registered, matched, active, busy 0 (221 ms), retain 9>
  | |   +-o Xbox Kinect Audio, © 2011 Microsoft Corporation. All rights reserved.@fa131000  <class IOUSBDevice, id 0x100003ce9, registered, matched, active, busy 0 (7 ms), retain $
  | |   +-o Xbox NUI Camera@fa133000  <class IOUSBDevice, id 0x100003cf1, registered, matched, active, busy 0 (31 ms), retain 9>
```

Anything I am missing or doing wrong?

**Comment by blueeaglex** [comment]
Hi!  See you again! 
I have no idea of Mac OS.  According to my experience, the device may not be detected if you application was crashed without status clean up during the last running.
But on my windows 7 64 bit, my StructureSensor couldn't be detected either. And the reason is clearly not the one above.  
It seems that both of us were searching in the dark now. 
Where are they, I wonder?

**Comment by QuinAsura** [comment]
I have used openni2 drivers for extracting depth images both in ubuntu 14.04 and win 7 64bit. It was extremely easy in windows all I had to do was install the precompiled openni2 drivers. For linux I followed a tutorial on setting up openni2 for nvidia jetson and modified it according to my needs.

**Comment by blueeaglex** [comment]
Thanks! QuinAsura:
You informed me something.  I download the prebuilt openni2 drivers for windows and it works! 
Maybe something about run-time version prevent my own built from working.

**Comment by ningt** [comment]
@florianletsch Have you solved it? I am having the same problem

**Comment by blueeaglex** [comment]
@ningt 
I got the same problem with my compiled OpenNI2.
But I succeed with prebuilt one.
Have you tried the prebuilt OpenNI2?

**Comment by ningt** [comment]
@blueeaglex 
I'm running the pre-compiled samples under `Samples/Bin` and I'm using mac os. What can get the prebuilt OpenNI2? Thanks!

**Comment by blueeaglex** [comment]
@ningt You can get it from here.
http://www.structure.io/openni

**Comment by ningt** [comment]
@blueeaglex 
yes I'm using the pre-built version from the same link you provided. I followed the documentation to install OpenNI by running `./install.sh`, then running the samples under `Samples/Bin` gives me `No device found error` but apparently my device is connected because I can run openkinect samples.

**Comment by yanghansyuan** [comment]
I got same problem with @florianletsch. So let me get clear,the prebuilt OpenNI2 is on http://www.structure.io/openni. Is that mean the Beta one?  And the compiled version is the newest branch here?

**Comment by yanghansyuan** [comment]
Also,I'm wondering should I install NITE and SensorKinect for this?

**Comment by RaitoBezarius** [comment]
I am having the same issue, it seems like that even with NITE and SensorKinect, it does not do anything.

OS: Arch Linux (kernel 4.3) with libfreenect (examples working).

**Comment by jselikof** [comment]
In a terminal window, cd to the Samples/Bin folder.  Run the sample apps as, e.g., ./SimpleViewer.

**Comment by ashokbugude** [comment]
Hi, I am trying to run SimpleViewer in Linux 64 bit using Kinect xbox360 , but i get below error

After initialization:

SimpleViewer: Device open failed:
DeviceOpen using default: no devices found

**Comment by rossanag** [comment]
@ashokbugude could you solve it? I am on linux also and facing the same problem.

**Comment by ashokbugude** [comment]
No I couldn't solve it

**Comment by josuerocha** [comment]
I am having the same problem on UBUNTU 16.04 now. Can anyone help please? I need to run this on Linux for a project. Thanks.

**Comment by rossanag** [comment]
@josuerocha I finally solved it, the solution is in another thread. Hope it works for you too.
[](https://github.com/occipital/OpenNI2/issues/101)

**Comment by josuerocha** [comment]
@rossanag Thanks for your reply, which thread is it?

**Comment by rossanag** [comment]
Click over the #101

**Comment by josuerocha** [comment]
Thank you so much.
