### ISSUE TITLE
Complie error

### ISSUE THREAD

**Issue by LiliMeng** [occipital/OpenNI2#68]
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `InfiniTAM::Engine::OpenNIEngine::getImages(ORUtils::Image<ORUtils::Vector4<unsigned char> >*, ORUtils::Image<short>*)':
OpenNIEngine.cpp:(.text+0x35d): undefined reference to `oniStreamReadFrame'
OpenNIEngine.cpp:(.text+0x373): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x3a5): undefined reference to `oniStreamReadFrame'
OpenNIEngine.cpp:(.text+0x3bb): undefined reference to `oniFrameRelease'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `InfiniTAM::Engine::OpenNIEngine::~OpenNIEngine()':
OpenNIEngine.cpp:(.text+0x42f): undefined reference to `oniStreamStop'
OpenNIEngine.cpp:(.text+0x4ab): undefined reference to `oniStreamStop'
OpenNIEngine.cpp:(.text+0x57f): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x59b): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x74c): undefined reference to `oniShutdown'
OpenNIEngine.cpp:(.text+0x771): undefined reference to `oniDeviceClose'
OpenNIEngine.cpp:(.text+0x791): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x7b1): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x7d1): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x7f1): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x804): undefined reference to `oniDeviceClose'
OpenNIEngine.cpp:(.text+0x879): undefined reference to `oniFrameRelease'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `InfiniTAM::Engine::OpenNIEngine::OpenNIEngine(char const*, char const*, bool, ORUtils::Vector2<int>, ORUtils::Vector2<int>)':
OpenNIEngine.cpp:(.text+0xc32): undefined reference to `oniInitialize'
OpenNIEngine.cpp:(.text+0xc37): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0xca0): undefined reference to `oniDeviceSetProperty'
OpenNIEngine.cpp:(.text+0xcc8): undefined reference to `oniDeviceSetProperty'
OpenNIEngine.cpp:(.text+0xce6): undefined reference to `oniDeviceCreateStream'
OpenNIEngine.cpp:(.text+0xcf3): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0xd30): undefined reference to `oniDeviceCreateStream'
OpenNIEngine.cpp:(.text+0xd3d): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0xd6c): undefined reference to `oniShutdown'
OpenNIEngine.cpp:(.text+0xd8d): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0xda9): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x1050): undefined reference to `oniStreamGetSensorInfo'
OpenNIEngine.cpp:(.text+0x10bd): undefined reference to `oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0x10d9): undefined reference to `oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0x12ba): undefined reference to `oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0x12f5): undefined reference to `oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0x1311): undefined reference to `oniStreamStart'
OpenNIEngine.cpp:(.text+0x1329): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x13de): undefined reference to `oniDeviceOpen'
OpenNIEngine.cpp:(.text+0x1412): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x1430): undefined reference to `oniShutdown'
OpenNIEngine.cpp:(.text+0x1451): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x146d): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x19e8): undefined reference to `oniStreamGetSensorInfo'
OpenNIEngine.cpp:(.text+0x1a47): undefined reference to `oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0x1a62): undefined reference to `oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0x1c1e): undefined reference to `oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0x1c5f): undefined reference to `oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0x1c7b): undefined reference to `oniStreamStart'
OpenNIEngine.cpp:(.text+0x1d01): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x1e2a): undefined reference to `oniDeviceSetProperty'
OpenNIEngine.cpp:(.text+0x1e34): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1e46): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1e65): undefined reference to `oniDeviceGetSensorInfo'
OpenNIEngine.cpp:(.text+0x1ed3): undefined reference to `oniDeviceGetSensorInfo'
OpenNIEngine.cpp:(.text+0x1f36): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1f41): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1f51): undefined reference to `oniDeviceClose'
OpenNIEngine.cpp:(.text+0x1fdf): undefined reference to `oniDeviceClose'
OpenNIEngine.cpp:(.text+0x1fe9): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1ff6): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x20b8): undefined reference to `oniDeviceGetInfo'
OpenNIEngine.cpp:(.text+0x20c7): undefined reference to `oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x20df): undefined reference to `oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x20f7): undefined reference to `oniDeviceIsCommandSupported'
OpenNIEngine.cpp:(.text+0x2128): undefined reference to `oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x21bf): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x2236): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x2356): undefined reference to `oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x236e): undefined reference to `oniDeviceIsCommandSupported'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `openni::OpenNI::waitForAnyStream(openni::VideoStream**, int, int*, int)':
OpenNIEngine.cpp:(.text._ZN6openni6OpenNI16waitForAnyStreamEPPNS_11VideoStreamEiPii[_ZN6openni6OpenNI16waitForAnyStreamEPPNS_11VideoStreamEiPii]+0x64): undefined reference to `oniWaitForAnyStream'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `openni::VideoStream::~VideoStream()':
OpenNIEngine.cpp:(.text._ZN6openni11VideoStreamD2Ev[_ZN6openni11VideoStreamD5Ev]+0x7a): undefined reference to `oniStreamDestroy'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `openni::Device::~Device()':
OpenNIEngine.cpp:(.text._ZN6openni6DeviceD2Ev[_ZN6openni6DeviceD5Ev]+0xa4): undefined reference to `oniDeviceClose'
collect2: error: ld returned 1 exit status
make[2]: *** [InfiniTAM] Error 1
make[1]: *** [CMakeFiles/InfiniTAM.dir/all] Error 2
make: *** [all] Error 2

**Comment by LiliMeng** [comment]
Just change the find_package(OpenNI QUIET)  to find_package(OpenNI2 QUIET)  in CMakeLists.txt

**Comment by jselikof** [comment]
This issue would be a better fit for theInfiniTAM repository.
