### ISSUE TITLE
I can't get more than 8fps out of ASUS Xtion at 1280x1024

### ISSUE THREAD

**Issue by mrcasty** [occipital/OpenNI2#70]
Does anyone know whether it is a limitation of the hardware or I must be simply doing something wrong? 

According to the specs, it should get 30fps at this resolution. I updated it to the latest firmware and I tried both USB 2.0 and USB 3.0 connectors. 

I also tried YUV422 mode which should supposedly transfer less data, but it didn't get any faster. That's why I'm starting to think the problem might be the device itself. 

EDIT: I also tried outdoors so, I don't think it is caused by low light conditions. 
 
Thanks!

**Comment by connerbrooks** [comment]
You may need to make the changes that are documented [here](http://com.occipital.openni.s3.amazonaws.com/Structure%20Sensor%20OpenNI2%20Quick%20Start%20Guide.pdf).

Change **PS1080.ini** replacing

```
;UsbInterface=2
```

with

```
UsbInterface=0
```

Hope that helps!

**Comment by mrcasty** [comment]
Thanks for your reply, but unfortunately it didn't run any faster :(

The call to openni::OpenNI::waitForAnyStream still takes 125ms or more at 1280x1024

**Comment by jselikof** [comment]
Referencing a comment here: https://www.youtube.com/watch?v=egDHPJKBm_o 
"About frame rate in 1280 mode.
Yes it is possible to run color camera in 30 fps mode with resolution 1280x1024 but without depth stream. With depth stream Xtion Pro can produce only 8 fps and this is camera limitation. On PC will be the same.﻿"
