### ISSUE TITLE
"Install" project in OpenNI.sln is incompatible on VS2013 and missing NuiApi.h error

### ISSUE THREAD

**Issue by ani-rudh** [occipital/OpenNI2#75]
Hello,
1.
I am a newbie to ComputerVision and I am trying to use OpenNI2 for getting RGB and Depth frames of a Kinect v2.0 . I have installed the Kinect for Windows 2.0 SDK and I am using MS VS2013 on x64 machine running Windows 10.
When I forked the OpenNI Kinect2 branch from the repo [https://github.com/occipital/OpenNI2/tree/kinect2] and tried to build the solution, The "Install" project under OpenNI.sln is incompatible with VS2013 and on build, I am getting "cannot find NuiApi.h" c1083 error in 2 of the projects.  (I am directly building the .sln after cloning a copy, am I missing something here?)

2. I get a LNK1104 error "cannot open XnLib.lib in Kinect2 project but it works with other projects like NiViewer.

3.
Does the precompiled binaries on Structure.io (OPENNI 2.2.0.33) include support for Kinect V2.0 sensor so that the above issue is irrelevant?

Please help me out as I am new to programming in general and very much new to CV as I told. 

![oni](https://cloud.githubusercontent.com/assets/15331399/12530146/eed767cc-c1d4-11e5-999f-72f798a06496.PNG)

**Comment by mvm9289** [comment]
Anirudh doubts were mostly resolved offline. Please, close this issue.

**Comment by ani-rudh** [comment]
Hello Miguel,

I'll surely do it by end of today.

Thanks and regards
Anirudh

**Comment by msalasg** [comment]
Hello, 

I am running basically in the same issue. 

I have installed the Kinect SDK 2.0  for Windows and I am using MS VS2015 on x64 machine running Windows 10. I cloned the  [https://github.com/occipital/OpenNI2](https://github.com/occipital/OpenNI2) repository, and I tried to build the OpenNI.sln I ran into the same issue that  compiler "cannot find NuiApi.h". 

I would really appreciate you could share the solution that worked for  ani-rudh. 

Thanks,
Marta

**Comment by mvm9289** [comment]
Hi Marta,

That file is from SDK 1.8 for Kinect v1 sensors. If you want to build the
Kinect v2 driver you must clone kinect2 branch:
https://github.com/occipital/OpenNI2/tree/kinect2

You can build the driver only, and put the resulting binaries wherever you
have your OpenNI2 installation, under the drivers directory.

I hope it helps.

Miguel.

**Comment by mvm9289** [comment]
Just to be clear: You are getting such error because the Kinect v1 driver
is built as part of the OpenNI project, and you don't have Kinect v1 SDK
installed.

Miguel.

**Comment by ani-rudh** [comment]
The actual solution that worked for me was to unload the Kinect 1 project from the solution and the rest builds successfully if the Kinect 2.0 driver is involved. Basically, unload all the projects that have Kinect 1.x SDK dependencies

**Comment by msalasg** [comment]
Sorry for the delay in the answer, took me a little bit to find the time to compile this again. 
Thank you for your replies. I mended my error, and now it works nicely. 
Thank you both!
