### ISSUE TITLE
DeviceOpen using default: no devices found

### ISSUE THREAD

**Issue by skymeson** [occipital/OpenNI2#76]
Using a Kinectv2 on Ubuntu 14.04

I've tried several branches and get the same message each time. A google search indicates other people with same issue but no resolution yet. 

Code builds fine, but does not recognize device. 

Output of lsusb

$ lsusb 
Bus 004 Device 002: ID 8087:8000 Intel Corp. 
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:8008 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 008: ID 045e:02c4 Microsoft Corp. 
Bus 002 Device 007: ID 045e:02d9 Microsoft Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04f2:b414 Chicony Electronics Co., Ltd 
Bus 001 Device 004: ID 8087:07dc Intel Corp. 
Bus 001 Device 008: ID 1532:0037 Razer USA, Ltd 
Bus 001 Device 009: ID 045e:02d9 Microsoft Corp. 
Bus 001 Device 006: ID 0b05:17fd ASUSTek Computer, Inc. 

Made sure that lib files are linked. 

$ sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.3.5 /lib/x86_64-linux-gnu/libudev.so.0

In Bin directory

cd OpenNI2-kinect2/Bin/x64-Release/
sudo ./SimpleViewer
After initialization:

SimpleViewer: Device open failed:
	DeviceOpen using default: no devices found

Device works properly with libfreenect without issues. 

Can somebody help explain what I am missing? 

Thanks!

**Comment by mvm9289** [comment]
Hi,

I don't think OpenNI2 supports kinect2 with linux. The current OpenNI2
kinect V2 driver from side branch
https://github.com/occipital/OpenNI2/tree/kinect2 is written on top of the
MS Kinect for Windows driver.

Thanks,

Miguel.

--------------------------------------------
* Email:                  mvm9289@gmail.com
* Phone number (Germany): +49 1764-7-314957
* Phone number (Spain):   +34 617-873-608
* Phone number (US):      +1 (408) 646-4533

**Comment by HenningJ** [comment]
There is an OpenNI2 driver for libfreenect2 over at https://github.com/OpenKinect/libfreenect2/tree/master/src/openni2
@skymeson you should probably ask [there](https://github.com/OpenKinect/libfreenect2/issues).

**Comment by skymeson** [comment]
It works now but I'm not sure I could describe how to repeat my steps. I installed libfreenect2 and copied drivers to different locations based on tutorials online and then it finally started working. 

One really silly thing is that I need to be in the root directory for it to run, otherwise I get an error.
cd /home/skymeson/kinect/OpenNI2-kinect2/Bin/x64-Release
./NiViewer
openDevice failed:
	DeviceOpen using default: no devices found

Instead if I run using 
cd /home/skymeson/kinect/OpenNI2-kinect2
./Bin/x64-Release/NiViewer

Now it works!

**Comment by weberhen** [comment]
Hi,
did someone manage to record the steps in order to make Kinect v2 work with libfreenect2 + OpenNi2 like @skymeson?
