### ISSUE TITLE
no device found -- windows with Kinect v2

### ISSUE THREAD

**Issue by harry19902002** [occipital/OpenNI2#79]
Kinect V2 and 2.0 SDK
windows10
vs 2013
I have compiled the Kinect V2 branch of this project. But it still shows "no device found". Should I change something ? Thank you!

**Comment by jselikof** [comment]
@harry19902002 try increasing the timeout referenced below to something like 2000 and let us know the results:
https://github.com/occipital/OpenNI2/commit/5e059eb7850ce2df94e89c18b677ddaeb7316333

**Comment by mvm9289** [comment]
https://github.com/occipital/OpenNI2/pull/57 was intended to resolve that issue. Would you please merge?
