### ISSUE TITLE
Develop Build Fails

### ISSUE THREAD

**Issue by djeffal-obeyda** [occipital/OpenNI2#84]
I'm trying to build the develop branch on linux
i got this error
```
XnStatus.cpp:47:17: error: ‘s_XN_OK_result’ defined but not used [-Werror=unused-variable]
 static XnStatus s_XN_OK_result = xnRegisterErrorCodeMessages(0, 0, 1, &s_OK_Data);
                 ^
cc1plus: all warnings being treated as errors
make[1]: *** [../Bin/Intermediate/x64-Release/libXnLib.a/XnStatus.o] Error 1
make: *** [ThirdParty/PSCommon/XnLib/Source] Error 2
```

**Comment by trotlinebeercan** [comment]
Rather than disable treating warnings as errors project-wide, it is best to simply set this specific warning to be ignored and continue to treat other (more serious) warnings as errors.

See: https://github.com/occipital/OpenNI2/commit/70ef9c80f2f3e5efa7bdf047bec1aae6a22b954d
