### ISSUE TITLE
build using android-studio

### ISSUE THREAD

**Issue by Cianjoo** [occipital/OpenNI2#87]
I already checked mentioned for android-studio.
but..I want to build on android-studio..
now we can't build using android-studio?
if can, please guide to me?:)

**Comment by jselikof** [comment]
Have you tried creating an Android Studio project from the source?

**Comment by Cianjoo** [comment]
yes! but I just can see java. I can't see
NiViewer
OpenNIForAndroid
SimpleRead
SimpleViewer for apk.
if yoi can,would you guide to me?

**Comment by jselikof** [comment]
It's definitely possible to build from Android Studio, but it's been over one year ago and unfortunately I no longer have the project files.  What's the motivation for building from Android Studio?

**Comment by Cianjoo** [comment]
hm,,actually I want to build and running niviewer on android device with structure sensor. 
so...do you know whether this is working or not with latest android studio?

**Comment by jselikof** [comment]
I'm not certain about the latest Android studio.  Have you tried following the steps to build for Android in the Readme?

**Comment by Cianjoo** [comment]
yes! I just different using android studio.

**Comment by Cianjoo** [comment]
would you help me?
how can I found below?
actually I can't figure out "OpenNIForAndroid"..
NiViewer
OpenNIForAndroid
SimpleRead
SimpleViewer

**Comment by jselikof** [comment]
@Cianjoo were you able to build using Android studio?

-jim

**Comment by masterchop** [comment]
Whats the point of OpenNI for android, this means that we can connect the kinect to our phone with otg and that should work ???? that would be a great integration, what about FPS?
