### ISSUE TITLE
DeviceOpen using default: no devices found

### ISSUE THREAD

**Issue by ashokbugude** [occipital/OpenNI2#88]
Below is the error generated in Linux 64 bit when I run SimpleViewer

After initialization:

SimpleViewer: Device open failed:
	DeviceOpen using default: no devices found

**Comment by tong** [comment]
Same here.

**Comment by ashokbugude** [comment]
I use xbox360 as hardware device,Openi works fine but OpenNI2  throws me the error.Just informin so that it might help in resolving  the issue.

**Comment by phaazon** [comment]
Same error here with a PrimeSense sensor (RD1.09).

**Comment by birgersp** [comment]
Same error here, using Ubuntu 16.04 if it matters

**Comment by jselikof** [comment]
Were you guys using the binaries from here: http://structure.io/openni or did you build them?  If you built the binaries, were you on the develop branch?

**Comment by birgersp** [comment]
For my case, I was built the binaries from the master branch. The pre-built binaries that you refering to yields the same error.

**Comment by jselikof** [comment]
Please try building on the develop branch.  What distribution/version of Linux are your running?

**Comment by birgersp** [comment]
Trying to build from the develop branch fails:

`make -C ThirdParty/PSCommon/XnLib/Source
make[1]: Entering directory '/home/birger/Workspace/doc/OpenNI2/ThirdParty/PSCommon/XnLib/Source'
g++ -MD -MP -MT "./../Bin/Intermediate/x64-Release/libXnLib.a/XnLib.d ../Bin/Intermediate/x64-Release/libXnLib.a/XnLib.o" -c -msse3 -Wall -O2 -DNDEBUG -I../Include -I../ThirdParty/LibJPEG  -fPIC -fvisibility=hidden -Werror -o ../Bin/Intermediate/x64-Release/libXnLib.a/XnLib.o XnLib.cpp
In file included from XnLib.cpp:21:0:
../Include/XnStatusRegister.h:76:18: error: ‘s_XN_ERROR_GROUP_NI0_result’ defined but not used [-Werror=unused-variable]
  static XnStatus s_##group##first##_result = xnRegisterErrorCodeMessages(group,
                  ^
../Include/XnStatus.h:97:2: note: in expansion of macro ‘XN_STATUS_MESSAGE_MAP_END_FROM’
  XN_STATUS_MESSAGE_MAP_END_FROM(group, 0)
  ^
../Include/XnStatusCodes.h:73:1: note: in expansion of macro ‘XN_STATUS_MESSAGE_MAP_END’
 XN_STATUS_MESSAGE_MAP_END(XN_ERROR_GROUP_NI)
 ^
../Include/XnStatusRegister.h:76:18: error: ‘s_XN_ERROR_GROUP_OS0_result’ defined but not used [-Werror=unused-variable]
  static XnStatus s_##group##first##_result = xnRegisterErrorCodeMessages(group,
                  ^
../Include/XnStatus.h:97:2: note: in expansion of macro ‘XN_STATUS_MESSAGE_MAP_END_FROM’
  XN_STATUS_MESSAGE_MAP_END_FROM(group, 0)
  ^
../Include/XnStatusCodes.h:218:1: note: in expansion of macro ‘XN_STATUS_MESSAGE_MAP_END’
 XN_STATUS_MESSAGE_MAP_END(XN_ERROR_GROUP_OS)
 ^
cc1plus: all warnings being treated as errors
../../BuildSystem/CommonCppMakefile:133: recipe for target '../Bin/Intermediate/x64-Release/libXnLib.a/XnLib.o' failed
make[1]: *** [../Bin/Intermediate/x64-Release/libXnLib.a/XnLib.o] Error 1
make[1]: Leaving directory '/home/birger/Workspace/doc/OpenNI2/ThirdParty/PSCommon/XnLib/Source'
Makefile:126: recipe for target 'ThirdParty/PSCommon/XnLib/Source' failed
make: *** [ThirdParty/PSCommon/XnLib/Source] Error 2`

Ubuntu 16.04

**Comment by jselikof** [comment]
Creating a symlink to libudev.so.0 as suggested in an earlier issue by @andreaskoepf solves "no devices found" problem.  

On Ubuntu 16.04:
sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.6.4 /lib/x86_64-linux-gnu/libudev.so.0

Reference: https://codeyarns.com/2014/05/06/depthsense-error-some-dll-files-are-missing/

SimpleViewer is a demo for sensors with an on-board RGB camera, so if run with the Structure Sensor will generate a message about not finding color stream.  Try NiViewer in the Tools folder to see the depth and IR streams.

Failure to build on the develop branch appears to be due to warnings treated as errors.  A separate issue has already been opened.

**Comment by birgersp** [comment]
No, this doesn't solve it for me. Same error.

**Comment by jselikof** [comment]
@birgersp what sensor are you using?

Please try running "strace -y ./NiViewer" and post the results.

**Comment by birgersp** [comment]
Here's the output.

[output.txt](https://github.com/occipital/OpenNI2/files/311723/output.txt)

**Comment by jselikof** [comment]
From the strace output: "No such file or directory) open("/usr/lib/x86_64-linux-gnu/libglut.so indicates freeGLUT is missing. You could try just getting freeglut:  "sudo apt-get install freeglut3-dev", but may as well get all of the prerequisites referenced in the "Building for Linux" section of the README.

**Comment by birgersp** [comment]
Strange, freeglut3 was and is installed.

`birger@birger-office:~$ sudo apt-get install freeglut3 freeglut3-dev 
[sudo] password for birger: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
freeglut3 is already the newest version (2.8.1-2).
freeglut3 set to manually installed.
freeglut3-dev is already the newest version (2.8.1-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
birger@birger-office:~$ ls /usr/lib/x86_64-linux-gnu/libglut.so
/usr/lib/x86_64-linux-gnu/libglut.so`

All the prerequisites should have been installed when I was first trying OpenNI. I'll go over that once more and double-check

**Comment by birgersp** [comment]
Seems everything is installed, expect openjdk-6-jdk which is no longer in the official repos for Ubuntu 16.04.

I have java 8 installed, and JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle/`. Could this be why it can't connect?

**Comment by jselikof** [comment]
That shouldn't matter.  

As a test I just now freshly installed 64 bit Ubuntu 16.04 LTS in a VirtualBox VM then did the following:
- Download OpenNI 2.2.0.33 Beta (x64) from structure.io/openni
- Ran "sudo ./install.sh" 
- Connected the Structure Sensor device to the VM
- Ran ./NiViewer in the Tools directory and received message about libglut.so.3, so did "sudo apt-get install freeglut3-dev"
- Ran ./NiViewer, receive "openDevice failed", then ran strace -y ./NiViewer and note "No such file" message about libudev.so.0
- Executed "sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.6.4 /lib/x86_64-linux-gnu/libudev.so.0" as above
- NiViewer now works

Could you try to replicate these steps from a fresh Ubuntu install?

- jim

**Comment by birgersp** [comment]
Yes, still get the same error, I'm afraid.

**Comment by jselikof** [comment]
Which Kinect device?

**Comment by birgersp** [comment]
Kinect for Windows

**Comment by jselikof** [comment]
@birgersp we do have an experimental kinect2 branch, but it's only for WIndows.

**Comment by birgersp** [comment]
Are you saying OpenNI2 is initially not meant for Kinect2? I'm confused

**Comment by mvm9289** [comment]
Kinect drivers source code is private. I wrote an OpenNI2 Kinect2 driver on
top of Microsoft drivers, the same way it's done for Kinec2. So in
occipital's OpenNI2 project you'll find such implementation in kinect2
branch, which isn't merged to master yet.

For Linux support, I've heard there's an OpenNI2 Kinect2 driver based off
libfreenect2, but you'll have to check it out from their repositories, not
occipital's.

Hope it helps.

Miguel.

--------------------------------------------
* Email:                  mvm9289@gmail.com
* Phone number (Germany): +49 1764-7-314957
* Phone number (Spain):   +34 617-873-608
* Phone number (US):      +1 (408) 646-4533

**Comment by birgersp** [comment]
Ok, thanks

**Comment by ashokbugude** [comment]
Hi I still face the same issue for Kinect V1
I was unable to run ReleaseVersion.py   Is it because of that

$ ./ReleaseVersion.py x64
Creating installer for OpenNI 2.2 x64
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2

**Comment by ManyuChang** [comment]
@ashokbugude   Have you solved the problem? I use kinect Xbox360 .

**Comment by ashokbugude** [comment]
Hi No, Its not solved

**Comment by ManyuChang** [comment]
@ashokbugude OK! Go on! I'm trying it!

**Comment by linux-rock** [comment]
sudo ./NiViewer
openDevice failed:
	DeviceOpen using default: no devices found

still the same after creating the symbolic links etc...
Any Help?

**Comment by linux-rock** [comment]
HEY GUYS, I Solved it, I made OpenNI 2.2.0.33 work on my Ubuntu 16.04 Xenial 'XBox 360 Kinect, I used this branch "git clone https://github.com/occipital/OpenNI2" I made LD_LIBRARY_PATH in /etc/environment as I made it in the ~/.bashrc , and /etc/ld.so.conf.d ,  and then I answered all the messages "strace -y ./NiViewer" brought, by just Symbolic links, and also I manually installed Oracle-Java-6,  If anyone here hasn't succeeded let me know so I can post my workflow from start to finish, because it's a little bit Long, Thank U all.

**Comment by linux-rock** [comment]
HEY GUYS, I Solved it, I made OpenNI 2.2.0.33 work on my Ubuntu 16.04 Xenial 'XBox 360 Kinect, I used this branch "git clone https://github.com/occipital/OpenNI2" I made LD_LIBRARY_PATH in /etc/environment as I made it in the ~/.bashrc , and /etc/ld.so.conf.d ,  and then I answered all the messages "strace -y ./NiViewer" brought, by just Symbolic links, and also I manually installed Oracle-Java-6,  If anyone here hasn't succeeded let me know so I can post my workflow from start to finish, because it's a little bit Long, Thank U all.

**Comment by Danyc0** [comment]
Hi @linux-rock could you post your full workflow please? I've tried everything else and it sounds like you've got a solution which might help, Cheers

**Comment by basantanickal** [comment]
Hi. I am trying to install OpenNI in ubuntu 16.04 to use Kinect for XBox 360. I  did the following as mentioned by @jselikof :

-  Download OpenNI 2.2.0.33 Beta (x64) from structure.io/openni
-     Ran "sudo ./install.sh"
-     Connected the Structure Sensor device to the VM
-     Ran "sudo apt-get install freeglut3-dev"
-     Ran ./NiViewer, received "openDevice failed", then ran strace -y ./NiViewer
-     Executed "sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.6.4 /lib/x86_64-linux-gnu/libudev.so.0" as above

But NiViewer doesn't work. I have uploaded the output of running strace in the attachment. Can someone see what's going wrong. I could not trace it out. Thanks.

[output.txt](https://github.com/occipital/OpenNI2/files/1121084/output.txt)

**Comment by billamiable** [comment]
Maybe you can have a look at here: https://codeyarns.com/2015/08/04/how-to-install-and-use-openni2/

**Comment by bkakilli** [comment]
I solved same problem by following the "how to use Structure Sensor with OpenNI 2" instructions in https://structure.io/openni, under CHANGES REQUIRED ON LINUX section.

Instruction for Linux is as following;
```
Step 1: Open the /etc/openni/GlobalDefaults.ini file
Step 2: Search for the line that says “;UsbInterface=2” (no quotes)
Step 3: Change that line to “UsbInterface=0” (no quotes)
Step 4: Save this change to the /etc/openni/GlobalDefaults.ini file.
```
Notice the removed semi-colon (;) as well.

Hope this helps others.
