### ISSUE TITLE
OpenNI2.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by yangmh93** [occipital/OpenNI2#91]
Hi all,
I'm currently trying to get the kinect2 branch to work. Everything builds successfully but then I get the title error. I'm not sure how to address this problem.
Cheers

**Comment by mvm9289** [comment]
Hard to guess with such limited information, but are you trying to run it
from Visual Studio while having the kinect2 driver project as default? If
so, you have to edit the project properties to set an appropriate debugging
application such as SimpleViewer. DLL's although being binaries, are not
applications and won't run by themselves.

Thanks,
Miguel.

**Comment by mvm9289** [comment]
Another thing that comes to my mind is that you might have built it for
64-bit, but trying to run a 32-bit application.

Miguel.

**Comment by yangmh93** [comment]
Setting the SimpleViewer seems to have solved that problem but now I get a

After initialization:
        Found no files matching 'C:\Program Files (x86)\OpenNI2-kinect2\Bin\Win32-Debug\OpenNI2\Drivers\*.dll'
SimpleViewer: Device open failed:
        DeviceOpen using default: no devices found

I've tried placing the kinect20.dll in that location but it doesn't recognize it as valid.

**Comment by mvm9289** [comment]
Did you build all OpenNI2 drivers? Or just the OpenNI2 framework? They are
separate things, and if driver projects aren't set as dependencies of the
OpenNI2 framework, they will likely be ignored.

Miguel.

**Comment by yangmh93** [comment]
Thank you Miguel for all the help. It seems to have fixed my issues.

**Comment by Niranjanabram** [comment]
I want to unsubscribe from this chat. Muting the threat isn't helping.
