### ISSUE TITLE
How to build SimpleViewer for android

### ISSUE THREAD

**Issue by nkwangyh** [occipital/OpenNI2#93]
I've successfully built several demos via android ndk, such as SimpleRead and MultipleStreamRead, which are able to run on android but only in terminal simulator. The README file says that SimpleViewer is also able to run on android tablets but I failed to build it with ndk(Actually I didn't find any Android.mk file under SimpleViewer folder). So do you have any idea about how to build SimpleViewer for android? Thank you very much. :)

**Comment by nkwangyh** [comment]
Ok, I work it out. And I'm going to share some of my experience.
Since the README file says that you can open SimpleRead, SimpleViewer, and NiViewer with eclipse at root directory of OpenNI2. But what's important is first you need to checkout to the develop branch. If not, you'll get nothing.
After checkout to develop branch, you'll get the aforementioned three projects as well as a NDK project OpenNIForAndroid which provide shared libraries for the rest three projects.

One more issue is that you may not get it done without root privilege. You can first get it by "su", and then export root directory of ndk to PATH since eclipse need ndk-build to compile the NDK project. After that, by building all, you'll get it done. :)

**Comment by jselikof** [comment]
@nkwangyh glad you worked it out!

-jim
