### ISSUE TITLE
[Documentation] OpenNI & Structure Sensor 

### ISSUE THREAD

**Issue by lmEshoo** [occipital/OpenNI2#95]
Hi I have a structure sensor connected to a Raspberry pi 3. I installed OpenNI on the pi. I would like to to know how to interface with the Structure Sensor, in any language. Ideas?

**Comment by jselikof** [comment]
@lmEshoo were you able to build and run SimpleRead?

-jim

**Comment by LGinC** [comment]
http://com.occipital.openni.s3.amazonaws.com/OpenNI_Programmers_Guide.pdf
no thanks

**Comment by LGinC** [comment]
C/C++ and Java

**Comment by lmEshoo** [comment]
That's awesome, so i've been playing with MWClosestPointApp and it's working well. I am wondering if there are any samples that can detect a person or gesture or a square or a circle?(something unique)

I am also getting depth, ir and xyz images. Any idea how to do image recognition (not live feed) to look for the above? Thanks!

**Comment by LGinC** [comment]
sorry,NITE doesn't support Arm-Linux anymore.
I can not find to the middleware that can detect a person too.
oh, I miss the SDK of Micorosoft.
Maybe you will find something in [openni.ru](openni.ru)

**Comment by LGinC** [comment]
@lmEshoo WindowsMobile? I think it is Windows10 Mobile.    Lumia or Microsoft？
